site_name: GTP-Guard
copyright: Copyright &copy; 2023 - 2026 Alexandre Cassen
repo_url: https://github.com/acassen/gtp-guard
repo_name: GTP-Guard
theme:
  name: material
  logo: assets/logo.png
  favicon: images/favicon.ico
#  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
    - header.autohide
  palette:
    - scheme: default
      primary: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
extra:
  homepage: https://www.gtp-guard.org
  generator: false
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Home: index.md
  - Articles:
    - articles/index.md
    - "5G UPF: Smart Session Placement": articles/5g-upf-smart-session-placement.md
    - "5G UPF: From Flow Steering to Session Affinity": articles/5g-upf-from-flow-steering-to-session-affinity.md
    - Per-Core CPU Load Measurement: articles/cpu_load_measurement.md
    - "5G UPF: Pump Up the Volume!": articles/5g-upf-pump-up-the-volume.md
plugins:
  - search
  - tags
  - privacy:
      enabled: true
      cache: true
      cache_dir: .cache/plugins/privacy
      assets: true
      assets_fetch: true
      assets_fetch_dir: assets/external
