/* SPDX-License-Identifier: AGPL-3.0-or-later */
/*
 * Soft:        The main goal of gtp-guard is to provide robust and secure
 *              extensions to GTP protocol (GPRS Tunneling Procol). GTP is
 *              widely used for data-plane in mobile core-network. gtp-guard
 *              implements a set of 3 main frameworks:
 *              A Proxy feature for data-plane tweaking, a Routing facility
 *              to inter-connect and a Firewall feature for filtering,
 *              rewriting and redirecting.
 *
 * Authors:     Alexandre Cassen, <acassen@gmail.com>
 *
 *              This program is free software; you can redistribute it and/or
 *              modify it under the terms of the GNU Affero General Public
 *              License Version 3.0 as published by the Free Software Foundation;
 *              either version 3.0 of the License, or (at your option) any later
 *              version.
 *
 * Copyright (C) 2023-2026 Alexandre Cassen, <acassen@gmail.com>
 */
#pragma once

#include <stdint.h>
#include <stdbool.h>
#include "gtp_stddef.h"
#include "id_pool.h"
#include "ip_pool.h"
#include "list_head.h"

enum gtp_range_partition_type {
	GTP_RANGE_PARTITION_TEID,
	GTP_RANGE_PARTITION_IPV4,
	GTP_RANGE_PARTITION_IPV6,
	GTP_RANGE_PARTITION_TYPE_MAX,
};

/* One sub-range within a range-partition */
struct gtp_range_part {
	int			part_id;
	union {
		struct id_pool	*id_pool;	/* GTP_RANGE_PARTITION_TEID */
		struct ip_pool	*ip_pool;	/* GTP_RANGE_PARTITION_IPV4/IPV6 */
	};
};

struct gtp_range_partition {
	char			name[GTP_NAME_MAX_LEN];
	int			type;		/* enum gtp_range_partition_type */
	struct gtp_range_part	*parts;		/* sorted array, size nr_parts */
	int			nr_parts;
	bool			auto_split;	/* parts generated by split command */
	char			split_range[GTP_STR_MAX_LEN]; /* original range arg for config write-back */
	int			split_count;
	int			refcnt;
	struct list_head	next;
};

/* Prototypes */
struct gtp_range_partition *gtp_range_partition_get(const char *name);
struct gtp_range_partition *gtp_range_partition_alloc(const char *name);
int gtp_range_partition_free(struct gtp_range_partition *rp);
int gtp_range_partition_destroy(void);
struct gtp_range_part *gtp_range_partition_get_part(struct gtp_range_partition *rp, int part_id);
struct gtp_range_part *gtp_range_partition_get_part_by_index(struct gtp_range_partition *rp, int idx);
int gtp_range_partition_add_part(struct gtp_range_partition *rp, int part_id, void *pool);
int gtp_range_partition_del_part(struct gtp_range_partition *rp, int part_id);
int gtp_range_partition_split(struct gtp_range_partition *rp, const char *range_str, int count);
int gtp_range_partition_split_clear(struct gtp_range_partition *rp);
